name: Deploy to EC2 via Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy HTML to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Upload to a temporary directory
          scp -i private_key.pem -o StrictHostKeyChecking=no index.html $USER@$HOST:/tmp/index.html

          # Move into Nginx's web root using sudo
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            sudo mv /tmp/index.html /usr/share/nginx/html/index.html
            sudo chown nginx:nginx /usr/share/nginx/html/index.html || sudo chown www-data:www-data /usr/share/nginx/html/index.html
            sudo systemctl reload nginx
          EOF

          rm -f private_key.pem
